### PR TITLE
Fix url encoding of local document urls

### PR DESCRIPTION
**Pull request by rhyshort**
Local documents should not be url encoded, remove / encoding so url
is correctly generated as _local/mylocal instead of _local&2FmyLocal

reviewer @tomblench 
reviewer @ricellis

### CODE REVIEW

**Comment by ricellis** [comment]
Is a new test needed?

**Comment by rhyshort** [comment]
Well I don't think so because we have test coverage for _local doc urls by making use of them during replication for checkpoint docs. But we can add some specifically to test for this for peace of mind

**Comment by tomblench** [comment]
Agree that a test is needed to check that the URL string is the expected value

**Comment by rhyshort** [comment]
@tomblench @ricellis test added in 69db968

**Comment by ricellis** [comment]
+1

**Comment by tomblench** [comment]
+1

**Pull request merged**
