### PR TITLE
Simplify `Database` method names

### PR DESCRIPTION
**Pull request by tomblench**
As per #413 "naming proposal for Database methods (create, delete) instead of createDocumentFromRevision"

Should we also rename others: "getEventBus()" → "eventBus" and "getPath" → "getPath"?

### CODE REVIEW

**Comment by rhyshort** [comment]
@tomblench I'm confused about `getPath` to `getPath` did you miss some characters?

**Comment by rhyshort** [comment]
I'm not keen on `getAll` and `getAllIDs` but I can't really think of anything better all I have so far I've come up with `listDocuments` and `listIDs`.

**Comment by tomblench** [comment]
Sorry, I meant getPath → path

**Comment by tomblench** [comment]
I'm not a fan of `listDocuments` as "list" implies only getting some kind of primary key and not the whole document. I would be happier to change this to `get` and have the method signature and javadoc do the work of conveying to the user that it gets multiple documents based on certain criteria.

Not at all sure about the IDs one, maybe `getIds`?

**Comment by tomblench** [comment]
Agreed

**Pull request merged**
