### PR TITLE
Do not close SQLDatabaseQueue's database directly

### PR DESCRIPTION
**Pull request by rhyshort**
Use SQLDatabaseQueue's shutdown method to close the database,
without explicitly closing the underlying database from the datastore.

BugzId: 47163

reviewer @tomblench 
reviewer @brynh

### CODE REVIEW

**Comment by tomblench** [comment]
@rhyshort I wonder if you can take the opportunity to do another refactor here and remove the dbOpen flag. You can use queue.isShutdown() instead because If the queue is open and ready for business then the database is implicitly open.

**Comment by tomblench** [comment]
↑ or you could do this in #128, they both are related to this.

**Comment by tomblench** [comment]
+1 :+1:

**Comment by brynh** [comment]
+1

**Pull request merged**
