### PR TITLE
docs: ReplicationFactory superseded by ReplicatorBuilder

### PR DESCRIPTION
**Pull request by jo**

### CODE REVIEW

**Comment by rhyshort** [comment]
Hi @jo thanks for catching this, can you sign the CLA as mentioned in the [CONTRIBUTING.md](https://github.com/cloudant/sync-android/blob/master/CONTRIBUTING.md#contributor-license-agreement)? If you could copy me in (rhyshort@uk.ibm.com) on the email, that would be great as I can get this and #231 merged a little bit faster.

**Comment by rhyshort** [comment]
@jo we haven't received your CLA, do you still intend to contribute this change or shall I close this PR?

**Comment by jo** [comment]
Hi @rhyshort sorry for the delay, I still want to contribute and will send the CLA soon. Thanks for catching up!

**Comment by rhyshort** [comment]
@jo Great, we have your CLA, merging this and #231, thanks again :)

**Comment by jo** [comment]
You're welcome, thanks for merging :+1:

**Pull request merged**
