### PR TITLE
Correct creation of replications

### PR DESCRIPTION
**Pull request by mikerhodes**
This updates docs to put username and password in the URL.

It also changes the creation of replicator objects to use the `oneway(source, target)` shorthand.

reviewer @gadamc 
reviewer @tomblench

### CODE REVIEW

**Comment by gadamc** [comment]
So, `oneway(source, target)` is the deprecated method, right? You want to document using that instead of the `Push/PullReplication` objects ?

**Comment by tomblench** [comment]
@gadamc is right about the deprecation. It needs to look like this:

```java
PushReplication push = new PushReplication();
push.source = ds;
push.target = uri;
Replicator replicator = ReplicatorFactory.oneway(push);
```

**Comment by mikerhodes** [comment]
Bum, will change back, this is the exact reason why I PRed this change :)

**Comment by mikerhodes** [comment]
@gadamc @tomblench please check the update.

**Comment by tomblench** [comment]
+1 :+1:

**Comment by gadamc** [comment]
I think we should fully remove the ReplicatorFactory.oneway(ds, uri) methods. They are essentially unusable given that the credentials are stripped from the URI and there's no way, that I can see, to easily provide authentication (though, somebody may be able to modify the HTTP headers???) 

https://github.com/cloudant/sync-android/blob/master/sync-core/src/main/java/com/cloudant/sync/replication/ReplicatorFactory.java#L75

https://github.com/cloudant/sync-android/blob/master/sync-core/src/main/java/com/cloudant/sync/replication/ReplicatorFactory.java#L108

https://github.com/cloudant/sync-android/blob/master/sync-core/src/main/java/com/cloudant/sync/replication/ReplicatorFactory.java#L117-L121

I guess this should be done in a separate PR...

**Comment by mikerhodes** [comment]
@gadamc yes, it does look pretty useless and yes, it needs a separate bug filed for it. If you're happy with this PR please leave a +1. We can file a new case to either not remove creds or remove the method.

**Comment by gadamc** [comment]
+1

**Pull request merged**
