### PR TITLE
Close cursors in AttachmentManager

### PR DESCRIPTION
**Pull request by Matulis**
Updated to match the rest of cursor closing code

[Editing to add reviewer]
reviewer @rhyshort

### CODE REVIEW

**Comment by mikerhodes** [comment]
Thanks for this. Unfortunately we're a bit behind on accepting contributions since becoming part of IBM; we're fixing this and I'll update with a comment when we have the process in place. Sorry for the delay.

**Comment by mikerhodes** [comment]
Okay, I finally sorted all the things out. We need you to sign a CLA before I can accept these changes. This is hopefully a quick process, you can email a signed version. See the details here:

https://github.com/cloudant/sync-android/blob/master/CONTRIBUTING.md#contributor-license-agreement

Once I have this, I can accept your PRs. I really appreciate your patience as I've worked this process out.

**Comment by mikerhodes** [comment]
Confirming signed CLA on file.

@rhyshort Could you check this over, you are more familiar with the code than me?

We have a holiday in the UK until Tuesday, so hopefully we can get this merged first thing next week.

Have a great weekend.

**Comment by rhyshort** [comment]
Looks good to me, merging

Thanks @Matulis

**Pull request merged**
