### PR TITLE
Remove ReplicatorFactory.oneway methods

### PR DESCRIPTION
**Pull request by rhyshort**
Remove ReplicatorFactory.oneway methods since they remove a the
user name and password the user provides in a URI.

BugzId: 46491

reviewer @gadamc 
reviewer @tomblench

### CODE REVIEW

**Comment by gadamc** [comment]
The sample app still uses the deprecated methods. 

Would be nice if there's a way to build the sample app as well as the main library inside our CI tool.

**Comment by rhyshort** [comment]
It shouldn't be, I'm sure I made the change to the sample first

**Comment by rhyshort** [comment]
Yeah it is fixed in pr #117

**Comment by gadamc** [comment]
Sorry, you're right!
+1

**Comment by tomblench** [comment]
Add a comment to the 'Unreleased' section of `CHANGES.md` so we don't forget to document this user-affecting change.

**Comment by rhyshort** [comment]
@tomblench aded entry to changes.md in 74b15be

**Comment by tomblench** [comment]
OK +1

**Pull request merged**
