### PR TITLE
Add deprecation notice

### PR DESCRIPTION
**Pull request by ricellis**
## Checklist

- [x] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](../blob/master/DCO1.1.txt)
- [x] Added tests for code changes _or_ test/build only changes
- [x] Updated the change log file (`CHANGES.md`|`CHANGELOG.md`) _or_ test/build only changes
- [x] Completed the PR template below:

## Description

Add deprecation notice

## Approach

Add notice to README and CHANGES.

## Schema & API Changes

Deprecation notice, library EOL.

## Security and Privacy

- "No change"

## Testing

- N/A documentation

## Monitoring and Logging

- "No change"

### CODE REVIEW

**Review by eiri — APPROVED** [review]

**Comment by jjrodrig** [comment]
Hi, very sad news 
We have built several mobile APPs with CouchDB and Cloudant Sync. Cloudant Sync has been a core piece on our architecture. 
I see the other deprecations on the Coludant/CouchDB client libraries and I'm a bit worried about the lack of tools around Cloudant/CouchDB... CouchDB community seems to be strong, but the CouchDB ecosystem is not at the same level. 

Do you know any other alternative to support this functionality?

**Comment by ricellis** [comment]
>I see the other deprecations on the Coludant/CouchDB client libraries and I'm a bit worried about the lack of tools around Cloudant/CouchDB

We are moving to next generation SDKs for Cloudant (that still work with CouchDB). We have new libs for [Go](https://github.com/IBM/cloudant-go-sdk), [Java](https://github.com/IBM/cloudant-java-sdk) (which should also run in Android), [Node.js](https://github.com/IBM/cloudant-node-sdk) and [Python](https://github.com/IBM/cloudant-python-sdk).

>Do you know any other alternative to support this functionality?

With increasingly good JS ecosystems in mobile I think [PouchDB](https://github.com/pouchdb/pouchdb/) is a good alternative. I'm not aware of anything native, possibly someone with a strong requirement for that will decide to fork or try something new in that space.

**Comment by janl** [comment]
@ricellis thanks for the list of replacements. I notice iOS is conspicuously missing?

**Comment by jjrodrig** [comment]
So, there is a new generation of API wrappers but no new mobile native sync clients?

**Comment by ricellis** [comment]
>I notice iOS is conspicuously missing?

We do not currently have plans for a new Swift SDK. Without a [server-side](https://forums.swift.org/t/december-12th-2019/31735) impetus the primary motivator for creating one would be for a modern base to [CDTDatastore](https://github.com/cloudant/CDTDatastore) (or a replacement), but at this time our focus is not on the offline-first/sync use case.

>So, there is a new generation of API wrappers but no new mobile native sync clients?

Correct.

**Review by mojito317 — APPROVED** [review]

**Comment by ricellis** [comment]
As there has been some discussion here just wanted to [point to a blog post describing in more detail Cloudant's SDK changes](https://blog.cloudant.com/2021/06/30/Cloudant-SDK-Transition.html) that I've also linked to from the repo notice.

**Pull request merged**
